### PR TITLE
Remove unnecessary collection creation to pass clippy check

### PR DESCRIPTION
**Pull request by chenziya**
Hi,

When I ran the clippy check, found that there were unnecessary collections creation, hence the clippy can't pass, so I created a pull reqeust to fix it.

Hope this PR makes sense.

Best Regards,
Jacob Chen

### CODE REVIEW

**Review by NingLin-P — APPROVED** [review]
LGTM, thanks!

**Comment by BusyJay** [comment]
Please fix DCO, so we can get it merged.

**Comment by chenziya** [comment]
Hi @BusyJay , PR updated.

**Review by BusyJay — APPROVED** [review]

**Comment by chenziya** [comment]
Hi @NingLin-P, seems need one more approval from you to get it merged.

**Review by NingLin-P — APPROVED** [review]

**Pull request merged**
