### PR TITLE
[Cargo.toml] Upgraded dependencies

### PR DESCRIPTION
**Pull request by SamuelMarks**

### CODE REVIEW

**Comment by ice1000** [comment]
Please fix conflicts and deal with CLA stuffs, thanks!

**Comment by BusyJay** [comment]
The PR is not valid anymore.

**Comment by SamuelMarks** [comment]
@BusyJay Well it is 2 years later… ok I've merged master and remade the commit.

[0001-Cargo.toml-datadriven-harness-proto-Cargo.toml-Upgra.patch](https://github.com/tikv/raft-rs/files/6614282/0001-Cargo.toml-datadriven-harness-proto-Cargo.toml-Upgra.txt)

Tried with nightly and stable but always got:
> Execute Command: "cargo" "build" "--all-features"
>
>    Compiling protobuf-build v0.12.3
> error[E0592]: duplicate definitions with name `generate_files`
>   --> .cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-build-0.12.3/src/protobuf_impl.rs:63:5
>    |
> 63 |     pub fn generate_files(&self) {
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ duplicate definitions for `generate_files`
>    | 
>   ::: .cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-build-0.12.3/src/prost_impl.rs:5:5
>    |
> 5  |     pub fn generate_files(&self) {
>    |     ---------------------------- other definition for `generate_files`
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0592`.

Saw this but doesn't seem relevant: https://github.com/tikv/client-rust/issues/122

Thoughts?

**Comment by BusyJay** [comment]
protobuf-codec and prost-codec should not be enabled at the same time, there should be something wrong with features configuration.

**Comment by SamuelMarks** [comment]
@BusyJay Ok well this was all found in your repo [here] after upgrading your dependencies (`cargo upgrade`) and running `cargo build --all-features`

**Pull request closed without merging**
