### PR TITLE
deps: Upgrade prost to 0.8

### PR DESCRIPTION
**Pull request by Xuanwo**
Fix https://github.com/tikv/raft-rs/issues/449

Signed-off-by: Xuanwo <github@xuanwo.io>

### CODE REVIEW

**Comment by Xuanwo** [comment]
Maybe I need to wait next release of protobuf-build?

**Comment by Xuanwo** [comment]
Closed for inactive and no response.

**Comment by BusyJay** [comment]
Oh, seems I miss the PR. Can you send a PR to prost-build to upgrade prost to 0.9 first?

**Comment by Xuanwo** [comment]
It looks `prost-build` has already updated: https://github.com/tokio-rs/prost/blob/master/prost-build/Cargo.toml#L22

**Comment by Xuanwo** [comment]
Ok, I got your ideas. I have sent a PR for it: https://github.com/tikv/protobuf-build/pull/58

**Pull request closed without merging**
