### PR TITLE
Update to Prost 0.11

### PR DESCRIPTION
**Pull request by agourlay**
This PR update to Prost 0.11.

Protobuf-build has been already updated https://github.com/tikv/protobuf-build/pull/63

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

**Comment by BusyJay** [comment]
protoc is also missing

**Comment by agourlay** [comment]
I need to find a way to install protoc across all OS configurations

**Comment by BusyJay** [comment]
How about using package manager instead? I'm worried about the permissions of secrets.

On Windows, it can be installed by `choco install protoc`, on MacOS it can be done by `brew install protobuf`, on Linux, it can be done by `sudo apt-get install protobuf-compiler`.

**Comment by agourlay** [comment]
@BusyJay No worries, I was able to use each package managers instead.

**Review by BusyJay — APPROVED** [review]
Thank you!

**Pull request merged**
